name: Release with Semantic Versioning and Changelog.

on: 
  workflow_call:
    outputs:
      releaseVersion: 
        value: ${{ jobs.release.outputs.releaseVersion }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    outputs:
      releaseVersion: ${{ steps.setOutput.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Release with semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install @semantic-release/changelog -D
          npm install @semantic-release/exec -D
          npx semantic-release
          echo ${{ env.RELEASE_VERSION }}
        
      - id: setOutput
        run: echo "::set-output name=version::${{ env.RELEASE_VERSION }}"