name: Release with Semantic Versioning and Changelog.

on: 
  workflow_call:
    outputs:
      releaseVersion:
        value: ${{ jobs.release.outputs.output1 }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.step1.outputs.releaseVersion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - id: step1
      - name: Release with semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install @semantic-release/changelog -D
          npm install @semantic-release/exec -D
          npx semantic-release
          echo "::set-output name=releaseVersion::${{ env.RELEASE_VERSION }}"